<?php

/**
 * @file
 * Google Maps module.
 *
 * Provides a Google Maps link/map formatter for simple Text fields. Note that
 * this is just a field formatter for Text fields, not a field. See README.txt
 * for more information.
 */

/**
 * Implements hook_theme().
 */
function yelp_w_map_theme() {
  return [
    'yelp_w_map_output' => [
      'variables' => [
        'yelp_data' => NULL,
        'yelp_logo' => NULL,
        'reviews' => NULL,
        'yelp_format' => NULL,
      ],
      'template' => 'yelp_w_map_output',
    ],
  ];
}
